### ISSUE TITLE
README link to neurodiversity.wiki

### ISSUE THREAD

**Issue by jtorreggiani** [alvarlagerlof/neurodiversity#101]
Hello! I love the idea for this project and would love to contribute! 

I noticed that the link to [neurodiversity.wiki](https://neurodiversity.wiki) in the `README.md` file was linking to https://github.com/jtorreggiani/neurodiversity/blob/main/neurodiversity.wiki. I updated the markdown to fix url's formatting.

I opened a pull request with the fix https://github.com/alvarlagerlof/neurodiversity/pull/100. Excited to contribute!

**Comment by alvarlagerlof** [comment]
Thanks for the fix! I've approved and merged your pull request!
