### ISSUE TITLE
Card links are not accessible

### ISSUE THREAD

**Issue by alvarlagerlof** [alvarlagerlof/neurodiversity#151]
So I've recently read that if a link does not immediately have a text tag inside of it it's not going to sound right in screen readers.

Currently, the links on the start page pointing to subpages using `LinkGrid.Item` contain a `h3` and a `p`.

The a should probably be inside the `h3` according to [this](https://stackoverflow.com/questions/7023512/which-is-more-correct-h1a-a-h1-or-ah1-h1-a#:~:text=H1%20elements%20are%20block%20level,not%20the%20other%20way%20around.). This presents an issue.

We want the whole card to be clickable, but we want the link around the title. I've read an article saying that the correct way ro approach this to capture clicks on the card, and then trigger a click on the link. Then you solve both issues.

**Comment by sabinevidal** [comment]
Hi @alvarlagerlof ! I'm happy to have a look at this issue! Have been doing reading on best accessibility practices on the web recently - so quite keen to put that into practice.

**Comment by alvarlagerlof** [comment]
@sabinevidal I've assigned you to this issue now!

**Comment by alvarlagerlof** [comment]
I ended up fixing this now
