### ISSUE TITLE
readme typos

### ISSUE THREAD

**Issue by csggene3** [alvarlagerlof/neurodiversity#243]
There are a couple typos in the readme. 
"It's also common to only focus on one conditon, even though knowledge about even though knowledge about most of them is lacking."

I'm something of a proofreader/copy editor and aspiring dev, but I tend to not offer fixes because I don't want to be perceived as "nit-picky." However, with a project such as this, where I have a personally vested interest (bipolar 1, schizoaffective, treatment resistant depression, social anxiety dis, etc) in its success and presentation in the best possible light, I don't think I'm being ocd or nit-picky; just trying to help in whatever way I feel I can. Code contributions can come later, if ever required, but what I can do immediately is scour the copy as a proofreader, and begin making the edits myself as opposed to pointing things out but not being proactive in rectifying what I find. If that would be considered useful, great. If not, no worries. Thanks for the project and all your efforts Alvar. =)

Gene

**Comment by alvarlagerlof** [comment]
That would be perfect! I'm quite terrible at editing myself. I'm dyslectic. You're not being "ocd" at all, in fact it has nothing to do with OCD :). The readme is the only the only thing I want edited here, the rest is better in the Google Docs linked in the Discord.

**Comment by alvarlagerlof** [comment]
@csggene3 Did you find yourself to the links in the Discord?

**Comment by alvarlagerlof** [comment]
I'll close this now. The links to the Google Docs are in the Discord at #doc-links. Here is a direct link.

https://discord.com/channels/835592135830011997/878383962546905119
