### ISSUE TITLE
Figure out a release/editorial process

### ISSUE THREAD

**Issue by alvarlagerlof** [alvarlagerlof/neurodiversity#4]
Currently, the website gets updated publicly whenever there is a push to main. This is not ideal and risky.

For content, it might include these steps
1. Someone fact checks it
2. Someone proofreads it
3. The ready text could be approved by someone/multiple someones
4. Merged to master

New code is submitted as a pull request
1. Tests are ran
2. The code is reviewed
3. The ready code could be approved by someone/multiple someones
4. We may also use branch protection rules to enforce parts of this process.

**Comment by alvarlagerlof** [comment]
I've added branch protection for main

**Comment by alvarlagerlof** [comment]
I'm torn on whether to create issues and pull requests for each page or just pull requests.

**Comment by sylwiavargas** [comment]
Perhaps, if it's coming from a thread we've discussed on Discord, we could just submit a PR. If it's a person from non-Discord community, they'd need to first submit an issue, get it okayed to work on and then submit a PR when they are done. We could even describe only this pathway in the contribution guide and bypass the issues within the team.

**Comment by alvarlagerlof** [comment]
> Perhaps, if it's coming from a thread we've discussed on Discord, we could just submit a PR. If it's a person from non-Discord community, they'd need to first submit an issue, get it okayed to work on and then submit a PR when they are done. We could even describe only this pathway in the contribution guide and bypass the issues within the team.

I like this. Will work on documenting that

**Comment by alvarlagerlof** [comment]
What do you think @lynkos @Toasterbirb ?

**Comment by alvarlagerlof** [comment]
The current setup probably works well enough already. I can do conversion and do it quickly.
