### ISSUE TITLE
Branch naming guidelines

### ISSUE THREAD

**Issue by alvarlagerlof** [alvarlagerlof/neurodiversity#41]
So far, I've just added branches with pretty much any name. But I think we should prefix them. Maybe something like this:

- content/draft-{page}: For new pages
- content/{page}-{change}: For content changes (spelling, fact checking, more content/sections)
- feature/{change}: For new features/improvements
- fix/{change}: For fixes

Feedback wanted

**Comment by alvarlagerlof** [comment]
I'm thinking we can turn this in to a wiki page later

**Comment by sylwiavargas** [comment]
This looks good! Definitely can be added as a part of [CONTRIBUTING.md](https://github.com/alvarlagerlof/neurodiversity/blob/main/CONTRIBUTING.md).

**Comment by alvarlagerlof** [comment]
Great, I'll add it @sylwiavargas
