### ISSUE TITLE
Should have an ADHD page

### ISSUE THREAD

**Issue by tekiegirl** [alvarlagerlof/neurodiversity#91]
Add an ADHD page with a similar structure to the current [OCD page](https://neurodiversity.wiki/ocd)

**Comment by tekiegirl** [comment]
I have forked and will aim to create a draft of this page ASAP

**Comment by alvarlagerlof** [comment]
> I have forked and will aim to update draft of this page ASAP

Please contact me on discord at alvar#6125 for this to go the correct way.
